//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 21:15:13  on 2002”N1ŒŽ9“ú
//
//	Generated for file: D:\home\prj\PalmCave\Rsc\SFCave.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"SFCave"
//
//	Palm App Version:		"0.04"


//	Resource: tFRM 1100
#define OptionForm                                1100	//(Left Origin = 4, Top Origin = 4, Width = 152, Height = 152, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1101)
#define OptionOKButton                            1101	//(Left Origin = 37, Top Origin = 125, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OptionCancelButton                        1102	//(Left Origin = 85, Top Origin = 125, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define OptionClearScoreCheckbox                  1104	//(Left Origin = 12, Top Origin = 52, Width = 120, Height = 16, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define OptionLevelLabel                          1106	//(Left Origin = 12, Top Origin = 20, Usable = 1, Font = Bold)
#define OptionButtonLabel                         1108	//(Left Origin = 12, Top Origin = 36, Usable = 1, Font = Bold)
#define OptionLevelList                           1103	//(Left Origin = 60, Top Origin = 20, Width = 64, Usable = 0, Font = Standard, Visible Items = 0)
#define OptionButtonList                          1110	//(Left Origin = 60, Top Origin = 36, Width = 64, Usable = 0, Font = Standard, Visible Items = 0)
#define OptionLevelPopTrigger                     1105	//(Left Origin = 52, Top Origin = 20, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1103)
#define OptionButtonPopTrigger                    1109	//(Left Origin = 52, Top Origin = 36, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1110)

//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 1000, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: Talt 1000
#define ClearScoreAlert                           1000
#define ClearScoreOK                              0
#define ClearScoreCancel                          1


//	Resource: tSTR 1000
#define AboutString                               1000	// "SFCave Ver.0.04 Copyright (c) 1998,2002 Sunflat   Control ribbon and avoid cave walls! You can use only"


//	Resource: PICT 1000
#define AppTitleBitmap                            1000

