What you need to build GentleMan

- m86k-plamos gcc tool chain
- palmos header files and library's
  (http://www.palmos.com/dev/)
- PilRC (http://www.ardiri.com/index.php?redir=palm&cat=pilrc)
- HandEra SDK header files
  (http://www.handera.com)
