//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 5:28:31 PM on Sunday, September 22, 2002
//
//	Generated for file: C:\popb\code\librarian\cw_r8\Rsc\librarian.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Librarian"
//
//	Palm App Version:		"2.0.0c"


//	Resource: tFRM 1000
#define ListForm                                  1000
#define ListNewButton                             1002
#define ListShowButton                            1004
#define ListFormatStatusList                      1003
#define ListCategoryList                          1008
#define ListBookStatusList                        1009
#define ListPrintStatusList                       1010
#define ListReadStatusList                        1011
#define ListCategoryPopTrigger                    1007
#define ListScrollUpRepeating                     1005
#define ListScrollDownRepeating                   1006
#define ListTable                                 1001

//	Resource: tFRM 2000
#define DetailsForm                               2000
#define DetailsOKButton                           2001
#define DetailsCancelButton                       2003
#define DetailsDeleteButton                       2005
#define DetailsNoteButton                         2008
#define DetailsPrivateCheckbox                    2007
#define DetailsReadCheckbox                       2016
#define DetailsCategoryLabel                      2002
#define DetailsPrivateLabel                       2006
#define DetailsBookStatusLabel                    2010
#define DetailsPrintStatusLabel                   2011
#define DetailsReadLabel                          2017
#define DetailsFormatLabel                        2018
#define DetailsCategoryList                       2009
#define DetailsBookStatusList                     2014
#define DetailsPrintStatusList                    2015
#define DetailsFormatList                         2020
#define DetailsCategoryPopTrigger                 2004
#define DetailsPrintStatusPopTrigger              2012
#define DetailsBookStatusPopTrigger               2013
#define DetailsFormatPopTrigger                   2019

//	Resource: tFRM 1200
#define EditForm                                  1200
#define EditDoneButton                            1203
#define EditDetailsButton                         1204
#define EditNoteButton                            1205
#define EditGraffitiShiftIndicatorGraffitiShift   1209
#define EditCategoryList                          1202
#define EditScrollUpRepeating                     1206
#define EditScrollDownRepeating                   1207
#define EditCategorySelTrigger                    1201
#define EditTable                                 1208

//	Resource: tFRM 1100
#define RecordForm                                1100
#define RecordDoneButton                          1101
#define RecordEditButton                          1102
#define RecordNewButton                           1103
#define RecordDisplayGadget                       1107
#define RecordCategoryLabel                       1106
#define RecordScrollUpRepeating                   1104
#define RecordScrollDownRepeating                 1105

//	Resource: tFRM 2200
#define PrefsForm                                 2200
#define PrefsOKButton                             2208
#define PrefsCancelButton                         2209
#define PrefsShowBookStatusCheckbox               2205
#define PrefsShowPrintStatusCheckbox              2206
#define PrefsShowReadUnreadCheckbox               2207
#define PrefsShowFormatCheckbox                   2210
#define PrefsShowInListLabel                      2201
#define PrefsShowAuthorTitlePushButton            2202
#define PrefsShowTitleAuthorPushButton            2203
#define PrefsShowTitleOnlyPushButton              2204
#define PrefsGroupID                              1

//	Resource: tFRM 2300
#define DeleteForm                                2300
#define DeleteOKButton                            2306
#define DeleteCancelButton                        2307
#define DeleteArchiveCheckbox                     2304
#define DeleteConfirmationIconBitMap              10005
#define DeleteDeletequestionLabel                 2303

//	Resource: tFRM 2400
#define AboutForm                                 2400
#define AboutOKButton                             2406
#define AboutApplicationIconBitMap                1000
#define AboutApplicationTitleLabel                2402
#define AboutVersionStringLabel                   2403
#define AboutCopyrightLabel                       2404
#define AboutEmailAddressLabel                    2405
#define AboutBlurb1Label                          2407
#define AboutBlurb2Label                          2408
#define AboutUnnamed2409Label                     2409
#define AboutBlurb4Label                          2410

//	Resource: tFRM 3000
#define SortForm                                  3000
#define SortSortingMessageLabel                   3000


//	Resource: Talt 1001
#define DeleteNoteAlert                           1001
#define DeleteNoteYes                             0
#define DeleteNoteNo                              1

//	Resource: Talt 1000
#define RomIncompatibleAlert                      1000
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define ExchangeErrorAlert                        1100
#define ExchangeErrorOK                           0


//	Resource: MBAR 1000
#define ListMenuBar                               1000

//	Resource: MBAR 1100
#define ListV20MenuBar                            1100

//	Resource: MBAR 1200
#define RecordMenuBar                             1200

//	Resource: MBAR 1300
#define RecordV20MenuBar                          1300

//	Resource: MBAR 1400
#define EditMenuBar                               1400

//	Resource: MBAR 1500
#define EditV20MenuBar                            1500

//	Resource: MBAR 1600
#define ListV35MenuBar                            1600

//	Resource: MBAR 1700
#define ListV40MenuBar                            1700

//	Resource: MBAR 1900
#define RecordV40MenuBar                          1900

//	Resource: MBAR 1800
#define EditV40MenuBar                            1800


//	Resource: MENU 1400
#define RecordV20Menu                             1400
#define RecordV20DeleteBook                       1400
#define RecordV20DuplicateBook                    1401
#define RecordV20AttachNote                       1403
#define RecordV20DeleteNote                       1404

//	Resource: MENU 1300
#define EditMenu                                  1300
#define EditUndo                                  1300
#define EditCut                                   1301
#define EditCopy                                  1302
#define EditPaste                                 1303
#define EditSelectAll                             1304
#define EditKeyboard                              1306
#define EditGraffitiHelp                          1307

//	Resource: MENU 1200
#define RecordMenu                                1200
#define RecordDeleteBook                          1200
#define RecordDuplicateBook                       1201
#define RecordAttachNote                          1203
#define RecordDeleteNote                          1204
#define RecordBeamBook                            1206

//	Resource: MENU 1100
#define ListRecordMenu                            1100
#define ListRecordBeamCategory                    1100

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsFont                               1000
#define OptionsAboutLibrarian                     1001

//	Resource: MENU 1500
#define OptionsV20Menu                            1500
#define OptionsV20AboutLibrarian                  1500

//	Resource: MENU 1700
#define OptionsV35Menu                            1700
#define OptionsV35Font                            1700
#define OptionsV35Security                        1701
#define OptionsV35AboutLibrarian                  1702

//	Resource: MENU 1600
#define RecordV40Menu                             1600
#define RecordV40DeleteBook                       1600
#define RecordV40DuplicateBook                    1601
#define RecordV40AttachNote                       1603
#define RecordV40DeleteNote                       1604
#define RecordV40BeamBook                         1606
#define RecordV40SendBook                         1607

//	Resource: MENU 1800
#define ListRecordV40Menu                         1800
#define ListRecordV40BeamCategory                 1800
#define ListRecordV40SendCategory                 1801


//	Resource: tSTR 1000
#define DetailsHelpString                         1000

//	Resource: tSTR 1100
#define NoTitleRecordString                       1100

//	Resource: tSTR 1200
#define NoAuthorRecordString                      1200

//	Resource: tSTR 1300
#define FindHeaderString                          1300

//	Resource: tSTR 1400
#define PrefsHelpString                           1400

//	Resource: tSTR 1500
#define DeleteHelpString                          1500

//	Resource: tSTR 1600
#define DupIndicatorString                        1600

//	Resource: tSTR 1700
#define UntitledSendString                        1700

//	Resource: tSTR 1800
#define NoAuthorSendString                        1800


//	Resource: tAIS 2000
#define CategoryAppInfoStr                        2000

//	Resource: tAIS 2100
#define EditFieldLabelsAppInfoStr                 2100

//	Resource: tAIS 2200
#define BookStatusAppInfoStr                      2200

//	Resource: tAIS 2300
#define PrintStatusAppInfoStr                     2300

//	Resource: tAIS 2400
#define ReadStatusAppInfoStr                      2400

//	Resource: tAIS 2500
#define FormatStatusAppInfoStr                    2500


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1101
#define Smallicon1bitBitmap                       1101

//	Resource: PICT 1102
#define Smallicon2bitBitmap                       1102

//	Resource: PICT 1108
#define Smallicon8bitBitmap                       1108


//	Resource: tbmf 1000
#define AboutIconBitmapFamily                     1000


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

